version: '3'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    pull_policy: never
    init: true
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate --quiet --tries=1 --spider https://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    image: mariadb:inception
    pull_policy: never
    init: true
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    image: wordpress:inception
    pull_policy: never
    init: true
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
      args:
        RD_PASS: ${RD_PASS}
    image: redis:inception
    pull_policy: never
    init: true
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  vsftpd:
    build:
      context: requirements/bonus/vsftpd
      dockerfile: Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    image: vsftpd:inception
    pull_policy: never
    init: true
    container_name: vsftpd
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception
    healthcheck:
      test: ["CMD-SHELL", "echo 'QUIT' | nc localhost 21 | grep '220' || exit 1"]
      interval: 30s
      timeout: 10s 
      retries: 3
    restart: always

  adminer:
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:inception
    pull_policy: never
    init: true
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
     - inception
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  website-nginx:
    build:
      context: requirements/bonus/website/nginx
      dockerfile: Dockerfile
    image: website-nginx:inception
    pull_policy: never
    init: true
    container_name: website-nginx
    depends_on:
      website-django:
        condition: service_healthy
    ports:
      - "5000:80"
    networks:
      - website
    volumes:
      - web-volume:/var/www/static
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  website-django:
    build:
      context: requirements/bonus/website/django
      dockerfile: Dockerfile
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DJANGO_DEBUG: ${DJANGO_DEBUG}
        DATABASE_URL: ${DATABASE_URL}
    image: website-django:inception
    pull_policy: never
    init: true
    container_name: website-django
    networks:
      - website
    volumes:
      - web-volume:/var/www/mysite/staticfiles
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  
  portainer:
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    image: portainer:inception
    pull_policy: never
    init: true
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pt-volume:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate --quiet https://localhost:9443/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/wonyang/data/wordpress
      o: bind

  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/wonyang/data/mariadb
      o: bind

  web-volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/wonyang/data/website
      o: bind
  
  pt-volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/wonyang/data/portainer
      o: bind


networks:
  inception:
    driver: bridge

  website:
    driver: bridge
